### ISSUE TITLE
Narrowing with company-capf closes popup

### ISSUE THREAD

**Issue by Wilfred** [racer-rust/emacs-racer#10]
If I have the following code:

```rust
fn foo(list: Vec<u64>) {
    list|
}
```

and I press `.`, as of #9, I get the usual company popup. However, if I press keys afterwards (e.g. `.a`) then as soon as I press `a` the popup closes.

@fbergroth any ideas what might be causing this? I'm not even sure if this is a genuine bug or if there's a company setting I'm missing.

**Comment by fbergroth** [comment]
See if #11 fixes it :)

**Comment by fbergroth** [comment]
I went ahead and merged it along with an update for the next melpa build of company.

Reopen the issue if it doesn't solve it.

**Comment by Wilfred** [comment]
I've just tested and it works nicely, thanks :)
