### ISSUE TITLE
Maintainership of emacs-racer

### ISSUE THREAD

**Issue by kngwyu** [racer-rust/emacs-racer#104]
For 3 reasons(
- I'm one of maintainers of racer since this April
- I'm using emacs-racer almost everyday to write Rust, and really love it
- This repository doesn't look well maintained

), last month I emailed @ane to ask for push access to this repository, but I haven't get reply yet.

So... can anyone give push access to me?
Or, should I maintain my fork of this repository?

**Comment by ane** [comment]
Hi,

Sorry I have been traveling and hiking outside the reaches of the Internet,
I will grant you push access presently.

Antoine

**Comment by ane** [comment]
Turns out I'm not a maintainer, ask @Wilfred or an owner

**Comment by kngwyu** [comment]
@ane 
Thanks, and sorry for misplaced email.

**Comment by kngwyu** [comment]
@Wilfred 
Thanks for invitation!

**Comment by Wilfred** [comment]
I'm sorry I've fallen behind on maintenance.

I've added you as a collaborator, so you can also create PRs, push commits etc. Please consider still creating PRs for new features or larger changes. Nonetheless, you have the power now :)
