### ISSUE TITLE
Type-at-point not working on racer 2.1.3

### ISSUE THREAD

**Issue by theindigamer** [racer-rust/emacs-racer#105]
For example, if you have the following code

```
use std::io::BufWriter as B;
fn foo() {
    let b = B::new();
}
```
when you move the cursor over `new`, the type of `new` doesn't show up in the bottom (is it called a minibuffer?). However, the same type-at-point does work on racer 2.0.6. I'm not sure what has changed in between, will try to narrow it down.

Tested with emacs 25.2.2 and racer-20180709.625

**Comment by kngwyu** [comment]
![image](https://user-images.githubusercontent.com/16046705/43694141-eac7ebc6-996c-11e8-82b3-e85f49ebd2fa.png)
![image](https://user-images.githubusercontent.com/16046705/43694149-f68e1368-996c-11e8-84c7-97658784bda5.png)

It looks a bug around `as` syntax :worried: 

I close this issue in favor of [upstream issue](https://github.com/racer-rust/racer/issues/917).
Thanks for reporting! :slightly_smiling_face:
