### ISSUE TITLE
Error running timer ‘company-quickhelp--show’

### ISSUE THREAD

**Issue by Iorest** [racer-rust/emacs-racer#113]
When I use company to edit my rust file,An error appeared 

Error running timer ‘company-quickhelp--show’: (error "Company: backend company-capf error \"Invalid use of ‘\\’ in replacement text\" with args (doc-buffer println!)")

This only happens when I try to company "println!",It seems to be "replace-regexp" error.

**Comment by Wilfred** [comment]
I believe this was fixed in bca8a6def1fa3d58e395c724d685b44f91f996bd.
