### ISSUE TITLE
Incorrect CARGO_HOME and RUST_SRC_PATH in racer--shell-command

### ISSUE THREAD

**Issue by guskovd** [racer-rust/emacs-racer#115]
process-environment values (rust-src-path and cargo-home) (https://github.com/racer-rust/emacs-racer/blob/master/racer.el#L202)
not available in temporary buffer:
(https://github.com/racer-rust/emacs-racer/blob/master/racer.el#L237)

Therefore, changing the environment variables RUST_SRC_PATH and CARGO_HOME or variables racer-rust-src-path, racer-cargo-home does not really change anything

**Comment by Wilfred** [comment]
Should be fixed in 9d8984e.

**Comment by Wilfred** [comment]
That said, it looks like `process-environment` is not a buffer-local value, so I don't see why changing to a temporary buffer would have changed its value.
