### ISSUE TITLE
Error while installing "cargo install racer"

### ISSUE THREAD

**Issue by shehzadaliqadri** [racer-rust/emacs-racer#122]
raza@Raza-Ubuntu:~$ cargo install racer
    Updating crates.io index
  Installing racer v2.1.19
   Compiling semver-parser v0.7.0
   Compiling arrayvec v0.4.10
   Compiling nodrop v0.1.13
   Compiling cfg-if v0.1.7
   Compiling libc v0.2.50
   Compiling rand_core v0.4.0
   Compiling lazy_static v1.3.0
   Compiling memoffset v0.2.1
   Compiling scopeguard v0.3.3
   Compiling stable_deref_trait v1.1.1
   Compiling byteorder v1.3.1
   Compiling proc-macro2 v0.4.27
   Compiling rustc-rayon-core v0.1.2
   Compiling smallvec v0.6.9
   Compiling rustc-rayon v0.1.2
error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/raza/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.9/lib.rs:33:32
   |
33 | #![cfg_attr(feature = "union", feature(untagged_unions))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /home/raza/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.9/lib.rs:35:37
   |
35 | #![cfg_attr(feature = "may_dangle", feature(dropck_eyepatch))]
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling unicode-xid v0.1.0
   Compiling bitflags v1.0.4
   Compiling syn v0.15.29
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `smallvec`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `racer v2.1.19`, intermediate artifacts can be found at `/tmp/cargo-installarnQai`

Caused by:
  build failed

**Comment by kngwyu** [comment]
We have to type `cargo +nightly install racer` because it depends on nightly library
