### ISSUE TITLE
Error on showing completion - Company: backend company-capf error "Symbol's function definition is void: block"

### ISSUE THREAD

**Issue by barometz** [racer-rust/emacs-racer#14]
Wasn't sure where to put this, but after finding https://github.com/JuliaLang/julia/issues/852 it seems plausible that this is something fixable within this package.

I've got emacs-nox 24 on Debian testing set up with racer and everything appears to work, but whenever I request a completion for anything I also get the following in my minibuffer:

    Error running timer `company-echo-show': (error "Company: backend company-capf error "Symbol's function definition is void: block\" with args (meta Broadcast)")

\*Messages* contains the following, where the first line appears as I open a rust file:

    Error during redisplay: (jit-lock-function 1) signaled (void-function block)
    Error during redisplay: (jit-lock-function 140) signaled (void-function block) [4 times]
    Error running timer `company-echo-show': (error "Company: backend company-capf error \"Symbol's function definition is void: block\" with args (meta Broadcast)")

The linked (and solved) issue in julia-mode seems to be essentially the same behaviour, but it's thoroughly unenlightening as to what the actual problem was. The core seems to be that something somewhere in the company pipeline is trying to use a function `block` which is not defined on some systems ("function definition is void", "void-function block")

Aaand I just noticed I'm getting the same error from eldoc: `eldoc error: (void-function block)` which is less of an issue as I'm okay with turning eldoc off. On the other hand, this increasingly suggests there's something weird with *my* system.

![2016-02-17 2](https://cloud.githubusercontent.com/assets/691020/13116621/df3aaa6e-d59c-11e5-9a2f-4a80b4b1ea64.png)

**Comment by fbergroth** [comment]
Maybe you're using `rust-mode` without compiling it?

A quick fix to get rid of the errors would be to put `(require 'cl)` early in your emacs init file.

**Comment by barometz** [comment]
Thanks! `(require 'cl)` did the trick. Odd. I did install rust-mode through melpa, and the compile log tells me things were compiled, so that's not where I went wrong. Glad to have a resolution, still wondering what was actually broken.

**Comment by fbergroth** [comment]
I have no idea either. You can run `M-x toggle-debug-on-error` so you'll get a backtrace to work with.

**Comment by barometz** [comment]
Turns out there's an elpa-rust-mode package in the Debian repos that works out of the box. I guess that counts as solved in context.
