### ISSUE TITLE
default `racer-cmd` to `~/.cargo/bin/racer` if not on path

### ISSUE THREAD

**Issue by ccmtaylor** [racer-rust/emacs-racer#16]
Now that racer is cargo-installable, would it make sense to search for it in cargo's default install directory?

**Comment by infinity0** [comment]
hm, arguably you should just put that in your PATH though? if racer does this, you could make the same argument for any other project to look in random paths instead of sticking solely with PATH

**Comment by ccmtaylor** [comment]
The existing code falls back to `/usr/local/bin/racer`, and my reasoning was that racer was more likely to be under `~/.cargo/bin/racer` since that's where [the default instructions](https://github.com/phildawes/racer#with-cargo-install) place the binary.

On OS X, emacs doesn't pick up modified PATH variables from the user's shell when launched from the GUI, so this would be one less corner to bump into.

**Comment by Dushistov** [comment]
+1 for default fallback as ~/.cargo/bin/racer
