### ISSUE TITLE
read RUST_DOC_PATH and add hyperlinks to the relevant parts

### ISSUE THREAD

**Issue by infinity0** [racer-rust/emacs-racer#17]
It would be really nice if I could click on each auto-completion suggestion and read their documentation. (Or in text mode, perhaps instead hit some key and just read it from inside emacs.)

It should be possible for RUST_DOC_PATH to either be a URL (e.g. to the online rust docs) or a local path (e.g. for [rust-doc](https://packages.debian.org/sid/rust-doc)).

**Comment by ane** [comment]
`company` has support for this, there's a possibility for adding documentation for each completion item, but racer itself doesn't read them (yet). So we need to implement that feature into Racer first, after that is done, implementing the feature is trivial.

**Comment by nickbroon** [comment]
I think https://github.com/phildawes/racer/issues/415 might be tracking adding the necessary support in racer.

**Comment by Wilfred** [comment]
Completed as part of #46.
