### ISSUE TITLE
s-split-up-to undefined

### ISSUE THREAD

**Issue by timcharper** [racer-rust/emacs-racer#2]
I don't have this emacs function: (`s-split-up-to`)

https://github.com/racer-rust/emacs-racer/blob/master/racer.el#L112

Which library is to define it?

I installed from melpa.

**Comment by timcharper** [comment]
Ah, found it. `s`, the long lost string library for emacs.

That function wasn't in `s-1.9.0`, which is the declared dependency for racer, and the version I had installed.

https://github.com/magnars/s.el/blob/1.9.0/s.el

**Comment by timcharper** [comment]
Either the dependency needs to point to the latest in `melpa`, dependency on the function should be removed, or the library should define a copy of it.

**Comment by Wilfred** [comment]
1.9.0 is the latest stable version of s.el. I've filed https://github.com/magnars/s.el/issues/78 to request a new release.

**Comment by Wilfred** [comment]
Fixed in #3.

**Comment by timcharper** [comment]
high fives, @Wilfred ! Thanks for getting this resolved.
