### ISSUE TITLE
`racer-find-definition` does not set mark

### ISSUE THREAD

**Issue by matthew-piziak** [racer-rust/emacs-racer#25]
`racer-find-definition` is a command that can cause the point to move a large distance. It should set the mark so that `C-u C-SPACE` jumps back to the usage. I believe that that behavior would match Emacs conventions. Currently `M-,` does this specifically for invocations to `racer-find-definition`, which is fine, but I'm not sure why it was implemented instead of `C-u C-SPACE`.

**Comment by Wilfred** [comment]
We explicitly use the tag-ring, so racer-find-definition is a drop-in replacement for `find-tag` (see commit message in 4dab4e0d9874fd1ea72d8b0d83abf88c273709b1).

**Comment by matthew-piziak** [comment]
That makes sense. Thank you!
