### ISSUE TITLE
HOME environment variable incorrectly concatenated 

### ISSUE THREAD

**Issue by cnaj** [racer-rust/emacs-racer#30]
If `CARGO_HOME` is not set, racer tries to set it to the default location `$HOME/.cargo`. This variable doesn't necessarily end with a `/` (as on my OS X system), resulting in an invalid path in `CARGO_HOME`. `cargo build` then fails with an error:

```
cargo build --verbose
error: Permission denied (os error 13)

Compilation exited abnormally with code 101 at Sun Jul 10 18:52:03
```

To fix, the path in `HOME` should be converted to a path before concatenating.

**Comment by dpc** [comment]
I was just about the report the same issue:

https://github.com/racer-rust/emacs-racer/blob/master/racer.el#L82

**Comment by cnaj** [comment]
I've opened a pull request: #31
