### ISSUE TITLE
Lisp error: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by fkarl423** [racer-rust/emacs-racer#33]
emacs-racer expects to find the Cargo.toml file in the base directory of the project. If it fails to find this file the following error appears:

`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  call-process("/home/user/.cargo/bin/racer" nil #<buffer  *temp*> nil "complete" "8" "18" "/home/user/test.rs" "/tmp/racer115770IJ")
  apply(call-process "/home/user/.cargo/bin/racer" nil #<buffer  *temp*> nil ("complete" "8" "18" "/home/user/test.rs" "/tmp/racer115770IJ"))
  process-lines("/home/user/.cargo/bin/racer" "complete" "8" "18" "/home/user/test.rs" "/tmp/racer115770IJ")
  apply(process-lines "/home/user/.cargo/bin/racer" "complete" ("8" "18" "/home/user/test.rs" "/tmp/racer115770IJ"))
  racer--call("complete" "8" "18" "/home/user/test.rs" "/tmp/racer115770IJ")
  racer--call-at-point("complete")
  racer-complete()
  racer-eldoc()
  #[0 "\302 \204###\205G#\303\304!\210\304\207	\203##\303	 !\207\305 \306 \211\204$#\304\202B###@=\2038#\307\310#\"\206B#\311#!\202B#\311#!\206B#\307\310#\"\303#!\266\203\207" [eldoc-last-message eldoc-documentation-function eldoc-display-message-p eldoc-message nil eldoc-current-symbol eldoc-fnsym-in-current-sexp apply eldoc-get-fnsym-args-string eldoc-get-var-docstring] 5 "\n\n(fn)"]()
  funcall(#[0 "\302 \204###\205G#\303\304!\210\304\207	\203##\303	 !\207\305 \306 \211\204$#\304\202B###@=\2038#\307\310#\"\206B#\311#!\202B#\311#!\206B#\307\310#\"\303#!\266\203\207" [eldoc-last-message eldoc-documentation-function eldoc-display-message-p eldoc-message nil eldoc-current-symbol eldoc-fnsym-in-current-sexp apply eldoc-get-fnsym-args-string eldoc-get-var-docstring] 5 "\n\n(fn)"])
  eldoc-print-current-symbol-info()
  #[0 "#\205##\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"]()
  apply(#[0 "#\205##\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"] nil)
  byte-code("r\301#\302H#\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 0 500000 t #[0 "#\205##\301 \207" [eldoc-mode eldoc-print-current-symbol-info] 1 "\n\n(fn)"] nil idle 0])`

It took quite some time to find the source of this error since the error message is not helpful at all.

The issue appears here: https://github.com/racer-rust/emacs-racer/blob/master/racer.el#L93

I would suggest to improve the error handling in that function and to insert a check for the file that returns a more helpful message if it is not found.

**Comment by Wilfred** [comment]
Looks like #28 broke this.
