### ISSUE TITLE
Racer can't load on Emacs 24.5

### ISSUE THREAD

**Issue by Nitori-** [racer-rust/emacs-racer#39]
I get this on startup:

    Warning (initialization): An error occurred while loading `/home/nitori/.emacs.d/init.el':

    Symbol's value as variable is void: xref-backend-identifier-at-point

    To ensure normal operation, you should investigate and remove the
    cause of the error in your initialization file.  Start Emacs with
    the `--debug-init' option to view a complete error backtrace.

The config is pretty basic:

    (use-package
      racer
      :ensure t
      :config
      (progn
        (add-hook 'rust-mode-hook #'racer-mode)
        (add-hook 'racer-mode-hook #'eldoc-mode)
        (add-hook 'racer-mode-hook #'company-mode)))

Seems related to the merge of #34.

**Comment by ane** [comment]
![http://i.imgur.com/iWKad22.jpg](http://i.imgur.com/iWKad22.jpg)

**Comment by ane** [comment]
That should fix it. We'll wait until Emacs 25 is released and create a version of the script that's backwards compatible.

*I should have tested it on Emacs 24.5...*

**Comment by vibhavp** [comment]
Sorry about that!
