### ISSUE TITLE
Provide an option for reusing racer help buffers

### ISSUE THREAD

**Issue by Wilfred** [racer-rust/emacs-racer#48]
Otherwise, users end up with a lot of buffers.

Alternatively (or additionally!) we could provide a 'kill all help buffers' command.

**Comment by NJBS** [comment]
Thanks for this! 👍

On Mon, Aug 29, 2016 at 11:22 PM, Wilfred Hughes < notifications@github.com [notifications@github.com] > wrote:
Closed #48 [https://github.com/racer-rust/emacs-racer/issues/48] via b5c6a71 [https://github.com/racer-rust/emacs-racer/commit/b5c6a715ae04de5d023dbefc1d2ade7783d3815f] .
