### ISSUE TITLE
Provide releases for melpa-stable

### ISSUE THREAD

**Issue by the-kenny** [racer-rust/emacs-racer#5]
Not everybody wants to run his daily development-setup on unstable packages from melpa. For those, melpa-stable provides a repository for *tagged* releases. All package authors have to do is that their releases in git.

It would be very nice if emacs-racer would start to tag the releases.

**Comment by Wilfred** [comment]
Totally agreed. I've tagged 0.0.2 so it should appear in MELPA stable.
