### ISSUE TITLE
racer not expanding tilde in racer-rust-src-path

### ISSUE THREAD

**Issue by tspiteri** [racer-rust/emacs-racer#57]
Up to some days ago, this initialization line used to be fine:

    (setq racer-rust-src-path "~/.local/src/rust/src")

Now I'm getting an error ".../racer exited with status 1", and had to change the initialization to:

    (setq racer-rust-src-path (expand-file-name "~/.local/src/rust/src"))

**Comment by Wilfred** [comment]
Hm, sorry about that.

I'm not sure what the best behaviour is here. Requiring users to expand the source path is a little more work, but it is explicit. What do you think? I suppose the likelihood of a directory starting with ~ is pretty much zero.

**Comment by tspiteri** [comment]
If the rust source is installed in the home directory, you either start the path with "/home/user/" or with "~/". And using ~ is much easier if you reuse one emacs initialization file across machines with different usernames.

**Comment by Wilfred** [comment]
OK, this should now be sorted. Let me know if not :)
