### ISSUE TITLE
Not completing with all valid choices

### ISSUE THREAD

**Issue by vermiculus** [racer-rust/emacs-racer#62]
I'm pretty confident that this is a racer bug, but I'm not sure how to test it with just the shell since it uses a namespace. I'll move the issue there when we confirm it's not emacs' (or my own) fault 😄 

I've been working through the tutorial, so there is nothing that doesn't meet the eye here. Racer is not providing the complete set of valid completions for the context in at least this case: `use rand::Rng; […] let a = rand::thread_rng().gen`.

![image](https://cloud.githubusercontent.com/assets/2082195/19518507/1d4f66a0-95cd-11e6-96fe-d706bd8b2739.png)

**Comment by Wilfred** [comment]
Sounds like it's a bug with racer itself rather than racer.el.

You can use `M-x racer-debug` in the latest version of racer.el to work out what racer command is being run.

**Comment by Wilfred** [comment]
I don't think there's anything we can do in racer.el for this bug, so I'm going to close this.
