### ISSUE TITLE
Tag and melpa version

### ISSUE THREAD

**Issue by nlamirault** [racer-rust/emacs-racer#7]
Melpa stable version seems to be 1.0.0 [1], but the last tag is 0.0.2 in Github [2].

[1] : http://stable.melpa.org/#/racer
[2] : https://github.com/racer-rust/emacs-racer/releases

**Comment by Wilfred** [comment]
This should now be fixed. The MELPA issue was fixed: https://github.com/milkypostman/melpa/issues/3205 and I've released 1.0.1 to ensure everyone gets the latest version.

**Comment by nlamirault** [comment]
Thanks !
