### ISSUE TITLE
`$ nil nil nil`

### ISSUE THREAD

**Issue by TyOverby** [racer-rust/emacs-racer#75]
I'm using spacemacs and I enabled the `rust` layer and get this whenever I open a rust file

#### `*racer-debug*`
```
The last racer command was:

$ cd nil
$ export nil
$ export nil
$ nil 

This command terminated with exit code nil.

No output on stdout.

No output on stderr.

The temporary file will have been deleted. You should be
able to reproduce the same output from racer with the
following command:

$ nil nil nil 

Please report bugs on GitHub.
```

**Comment by Wilfred** [comment]
Um, I'm not sure what the problem is. `racer-debug` is to help you see what racer command was run. You don't seem to have run any racer commands yet. Why are you looking a debug buffer?
