### ISSUE TITLE
Does racer triggers a build?

### ISSUE THREAD

**Issue by sebasmagri** [racer-rust/emacs-racer#77]
I was looking at honeypotio/searchspot today and when I opened its Cargo.toml a complete build of the project was triggered.

Would it be caused my emacs-racer?

**Comment by Wilfred** [comment]
It doesn't trigger a build, no. Racer will even work if your project doesn't currently build, e.g. if you haven't finished writing a function!

**Comment by Wilfred** [comment]
Also worth mentioning: M-x racer-debug will show you the last racer command run.

I think some flycheck configurations may build your project.

**Comment by sebasmagri** [comment]
It turned out to be Flycheck. Thanks!
